Repository matrixorigin/matrixone-operator, pull requests merged in 2022-05, with the labels that each got.

#64 Add architecture docs
  docs/architecture.md
  docs/img/thanos-prom.png
  docs/img/thanos_arch.png
Labels: doc

#83 Add api doc
  docs/api.md
Labels: doc

#87 Support default storage class config
  examples/tiny-cluster.yaml
  packages/matrixone-operator-0.1.0.tgz
  pkg/apis/matrixone/v1alpha1/matrixonecluster_types.go
  pkg/apis/matrixone/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/components/statefulset_control.go
Labels: bug

#91 optimize workflow
  .github/mergify.yml
  .github/workflows/workflows.yml
Labels: test-ci

#90 Update resource config
  packages/matrixone-operator-0.1.0.tgz
  pkg/apis/matrixone/v1alpha1/matrixonecluster_types.go
  pkg/apis/matrixone/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/components/statefulset_control.go
Labels: improvement, need-review

#95 Update getting_started.md
  docs/getting_started.md
Labels: doc, need-review

#96 Fix mergify
  .github/mergify.yml
Labels: test-ci, need-review

#93 [DOC]Update readme
  README.md
Labels: doc, reviewed

#94 [CI]Add update workflows
  .github/workflows/test_workflows.yml
  .github/workflows/update_workflows.yml
  examples/tencent-cluster.yaml
Labels: test-ci, need-review, do-not-merge

#100 [CI]Fix label on reviewed mergify config
  .github/mergify.yml
Labels: test-ci, need-review

#101 [FEATURE]Update default cluster config
  .github/actions/cluster/action.yml
  .github/actions/e2e_kind/action.yml
  .github/actions/helm_check/action.yml
  examples/tiny-cluster.yaml
  third_part/mo-docker/system_vars_config.toml
Labels: feature, need-review, do-not-merge

#102 [OPTIMIZE]Optimize make tools
  .gitignore
  .golangci.yml
  Makefile
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  deploy/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  packages/matrixone-operator-0.1.0.tgz
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: improvement, need-review

#103 [DOC]Optimize doc
  README.md
  docs/dev_guide.md
  docs/getting_started.md
  docs/operator.md
Labels: doc, need-review
