Repository matrixorigin/matrixone-operator, pull requests merged in 2022-06, with the labels that each got.

#110 docs(*): refine doc styles and typos
  Makefile
  README.md
  docs/api.md
  docs/architecture.md
  docs/cluster.md
  docs/dev_guide.md
  docs/getting_started.md
  docs/tencentcloud/tencent.md
Labels: doc, need-review

#111 update merfigy
  .github/mergify.yml
Labels: improvement, reviewed

#114 refactor: simplify code via generic
  .github/actions/dev_env/action.yml
  pkg/controllers/components/pod_control.go
  pkg/controllers/components/pvc_control.go
  pkg/controllers/components/service_control.go
  pkg/controllers/components/statefulset_control.go
  pkg/controllers/matrixone/event.go
  pkg/controllers/matrixone/handler.go
  pkg/controllers/matrixone/interface.go
  pkg/controllers/utils/utils.go
Labels: need-review, code-refactoring

#116 update controller: add owns
  packages/matrixone-operator-0.1.0.tgz
  pkg/controllers/matrixone/matrixonecluster_controller.go
Labels: improvement, reviewed

#118 chore: optimize local dev experience
  .github/actions/build_binary/action.yml
  .github/actions/checks/action.yml
  .github/actions/e2e_kind/action.yml
  .github/actions/helm_check/action.yml
  Makefile
  examples/kustomization.yaml
  examples/tiny-cluster.yaml
  go.mod
  hack/e2e.sh
  hack/kind-e2e.sh
  pkg/controllers/matrixone/suite_test.go
Labels: test-ci, need-review

#121 chore: fix typo and test mergify
  pkg/controllers/matrixone/predicates.go
Labels: test-ci, reviewed, can-merge
