Repository matrixorigin/matrixone-operator, pull requests merged in 2022-10, with the labels that each got.

#245 feat: wait dn to avoid cn crash on startup
  Makefile
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  hack/kind-e2e.sh
  pkg/controllers/mocluster/controller.go
  test/e2e/matrixonecluster_test.go
Labels: improvement

#246 test: add webhook compatiability test
  api/core/v1alpha1/cnset_webhook_test.go
  api/core/v1alpha1/dnset_webhook_test.go
  api/core/v1alpha1/logset_webhook_test.go
  api/core/v1alpha1/matrixonecluster_webhook_test.go
Labels: test-ci

#247 test: improve local e2e dev experience
  Dockerfile
  Makefile
  hack/kind-e2e.sh
  hack/lib.sh
Labels: test-ci, can-merge

#249 docs: add new get started document
  README.md
  charts/matrixone-operator/values.yaml
  docs/api.md
  docs/architecture.md
  docs/getting_started.md
  examples/logset.yaml
  examples/minio.yaml
  examples/mo-cluster.yaml
  hack/kind-e2e.sh
Labels: doc

#251 docs: add api reference generation
  Makefile
  api/Makefile
  api/config.yaml
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/cnset_webhook.go
  api/core/v1alpha1/cnset_webhook_test.go
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/dnset_webhook.go
  api/core/v1alpha1/dnset_webhook_test.go
  api/core/v1alpha1/groupversion_info.go
  api/core/v1alpha1/logset_helpers.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/logset_webhook_test.go
  api/core/v1alpha1/matrixonecluster_helpers.go
  api/core/v1alpha1/matrixonecluster_types.go
  api/core/v1alpha1/matrixonecluster_webhook.go
  api/core/v1alpha1/matrixonecluster_webhook_test.go
  api/core/v1alpha1/toml_config.go
  api/core/v1alpha1/toml_config_test.go
  api/core/v1alpha1/webhook.go
  api/core/v1alpha1/webhook_suite_test.go
  api/core/v1alpha1/webui_types.go
  api/core/v1alpha1/webui_webhook.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_webuis.yaml
  docs/reference/api-reference.md
Labels: doc

#253 feat: initialize mo credential can GC failed logset Pod
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/matrixonecluster_types.go
  api/core/v1alpha1/matrixonecluster_webhook_test.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  docs/reference/api-reference.md
  examples/mo-cluster.yaml
  hack/e2e.sh
  pkg/controllers/common/common.go
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/controller_test.go
  pkg/controllers/logset/sts_test.go
  pkg/controllers/mocluster/controller.go
  pkg/controllers/mocluster/controller_test.go
  test/e2e/logset_test.go
  test/e2e/matrixonecluster_test.go
Labels: feature, bug

#255 fix: credential ref should be in same namespace
  charts/matrixone-operator/values.yaml
  pkg/controllers/mocluster/controller.go
  pkg/controllers/mocluster/controller_test.go
Labels: bug

#256 docs: update document about credentials
  docs/getting_started.md
Labels: doc

#257 feat: auto delete orphaned PVC by default
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/logset_webhook_test.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  charts/matrixone-operator/values.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  docs/reference/api-reference.md
  pkg/controllers/cnset/resource.go
  pkg/controllers/dnset/resource.go
  pkg/controllers/dnset/resource_test.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/sts.go
  runtime/pkg/metrics/collector.go
  test/e2e/matrixonecluster_test.go
Labels: feature

#258 feat: expose CN address to clients
  pkg/controllers/cnset/resource.go
Labels: feature

#259 feat(test): add cn dn e2e test
  Makefile
  test/e2e/cnset_test.go
  test/e2e/dnset_test.go
  test/e2e/matrixonecluster_test.go
Labels: test-ci

#266 feat: add more condition metrics for resources
  cmd/operator/main.go
  runtime/pkg/metrics/collector.go
Labels: improvement

#267 feat: add phase to cluster status
  api/core/v1alpha1/matrixonecluster_types.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  pkg/controllers/mocluster/controller.go
Labels: feature

#219 fix: volumeMount create error
  api/core/v1alpha1/groupversion_info.go
  api/core/v1alpha1/matrixonecluster_types.go
  cmd/operator/main.go
  pkg/controllers/cnset/controller_test.go
  pkg/controllers/cnset/resource.go
  pkg/controllers/common/template.go
  pkg/controllers/dnset/controller_test.go
  pkg/controllers/dnset/resource.go
  pkg/controllers/logset/controller_test.go
  pkg/controllers/logset/sts_test.go
  pkg/utils/utils.go
  runtime/pkg/util/pod_util.go
Labels: bug

#269 add service address to cn
  Makefile
  pkg/controllers/cnset/resource.go
  pkg/controllers/cnset/utils.go
Labels: improvement
