Repository matrixorigin/matrixone-operator, pull requests merged in 2022-07, with the labels that each got.

#124 docs: add mo controller runtime RFC
  docs/rfc/2022-07-04-runtime.md
  docs/rfc/uml/runtime.png
  docs/rfc/uml/runtime.puml
Labels: can-merge

#126 docs: propose logset RFC
  docs/rfc/2022-07-04-logset.md
Labels: doc, reviewed, can-merge

#125 feat: init mo controller runtime framework
  runtime/go.mod
  runtime/go.sum
  runtime/pkg/reconciler/actor.go
  runtime/pkg/reconciler/event.go
  runtime/pkg/reconciler/reconciler.go
  runtime/pkg/reconciler/reconciler_test.go
  runtime/pkg/util/util.go
Labels: feature, reviewed, can-merge

#129 docs: add mo-operator RFC
  docs/rfc/2022-07-05-mo-cluster.md
Labels: doc, reviewed, can-merge

#130 style: fix rfc typos
  docs/rfc/2022-07-05-mo-cluster.md
Labels: doc, reviewed, can-merge

#131 chore: enfore all review comments are resolved before merging
  .github/mergify.yml
Labels: test-ci, reviewed, can-merge

#133 chore: update issue templates according to mo
  .github/ISSUE_TEMPLATE/10_bug_report.md
  .github/ISSUE_TEMPLATE/10_bug_report.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general_question.yml
  .github/ISSUE_TEMPLATE/performance_question.yml
  .github/ISSUE_TEMPLATE/refactoring_request.yml
Labels: can-merge

#144 refactor: separate code to different go modules
  cmd/infra/go.mod
  cmd/infra/go.sum
  go.mod
  go.sum
  images/operator/Dockerfile
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: reviewed, code-refactoring, can-merge

#147 feat(ci): add local license check
  .github/actions/checks/action.yml
  .licenserc.yml
  Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: test-ci, reviewed, can-merge

#146 fix(ci): use header for license check
  .github/actions/checks/action.yml
Labels: test-ci, reviewed, can-merge

#157 chore: disable ci checks during v0.1 iteration
  .github/workflows/test_workflows.yml
  .github/workflows/update_workflows.yml
Labels: test-ci

#158 feat: init mo-operator core/v1alpha1 CRD definition
  PROJECT
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/groupversion_info.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/matrixonecluster_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/go.mod
  api/go.sum
  api/temp
  cmd/operator/main.go
  go.mod
  pkg/apis/matrixone/v1alpha1/matrixonecluster_types.go
  pkg/controllers/components/service_control.go
  pkg/controllers/components/statefulset_control.go
  pkg/controllers/matrixone/handler.go
  pkg/controllers/matrixone/interface.go
  pkg/controllers/matrixone/matrixonecluster_controller.go
Labels: feature

#159 fix: fix license eye binary install command
  Makefile
Labels: bug, can-merge

#161 refactor: add crd gen for api module
  .gitignore
  Makefile
  api/Makefile
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/temp
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_cnsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_dnsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_logsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  deploy/crds/matrixone.matrixorigin.cn_cnsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_crds.yaml
  deploy/crds/matrixone.matrixorigin.cn_dnsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_logsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
Labels: code-refactoring, can-merge

#134 docs: add deployment topology overview and refine docs
  docs/rfc/2022-07-05-mo-cluster.md
Labels: doc, reviewed

#167 feat: implement basic logset reconciliation
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_cnsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_dnsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_logsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  deploy/crds/matrixone.matrixorigin.cn_cnsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_dnsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_logsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  go.mod
  go.sum
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/discovery.go
  pkg/controllers/logset/logset_controller.go
  pkg/controllers/logset/store.go
  pkg/controllers/logset/sts.go
  runtime/pkg/reconciler/actor.go
  runtime/pkg/reconciler/reconciler.go
  runtime/pkg/util/pod_util.go
  runtime/pkg/util/util.go
Labels: feature

#148 docs: refine logset bootstrap
  docs/rfc/2022-07-04-logset.md
Labels: doc, need-review

#169 feat: config managemeng and rolling-update for podset
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/toml_config.go
  api/core/v1alpha1/toml_config_test.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/go.mod
  api/go.sum
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_cnsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_dnsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_logsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  deploy/crds/matrixone.matrixorigin.cn_cnsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_dnsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_logsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  go.mod
  go.sum
  pkg/controllers/common/common.go
  pkg/controllers/common/common_test.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/sts.go
  runtime/pkg/fake/fake.go
  runtime/pkg/reconciler/actor.go
  runtime/pkg/util/util.go
Labels: feature, can-merge
