Repository matrixorigin/matrixone-operator, pull requests merged in 2022-09, with the labels that each got.

#205 fix: adapt operator to latest mo version
  examples/mo-cluster.yaml
  pkg/controllers/common/common.go
  pkg/controllers/dnset/resource.go
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/configmap.go
Labels: bug, can-merge

#206 feat: add matrixonecluster webhook
  api/Makefile
  api/core/v1alpha1/cnset_webhook.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/dnset_webhook.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/matrixonecluster_webhook.go
  api/core/v1alpha1/matrixonecluster_webhook_test.go
  api/core/v1alpha1/toml_config_test.go
  api/core/v1alpha1/webhook.go
  api/core/v1alpha1/webhook_suite_test.go
  api/go.mod
  api/go.sum
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  examples/mo-cluster.yaml
  pkg/controllers/logset/configmap.go
Labels: improvement, feature

#209 use official multi-arch image
  examples/logset.yaml
  examples/mo-cluster.yaml
Labels: improvement, can-merge

#216 chore: enable e2e test in CI
  *.go.new
  .github/actions/build_binary/action.yml
  .github/actions/checks/action.yml
  .github/actions/cluster/action.yml
  .github/actions/e2e/action.yml
  .github/actions/e2e_kind/action.yml
  .github/actions/helm_check/action.yml
  .github/workflows/test_workflows.yml
  hack/kind-e2e.sh
  runtime/pkg/reconciler/reconciler.go
  runtime/pkg/reconciler/reconciler_test.go
  test/kind-config.yml
Labels: improvement, can-merge

#217 fix deepcopy toml config
  .github/actions/build_image/action.yml
  .github/workflows/update_workflows.yml
  api/core/v1alpha1/toml_config.go
  api/core/v1alpha1/toml_config_test.go
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  pkg/controllers/cnset/controller.go
  test/e2e/matrixonecluster_test.go
Labels: can-merge, bug

#220 fix docker push
  .github/workflows/update_workflows.yml
  test/e2e/matrixonecluster_test.go
Labels: bug

#214 fix: webui runable
  Makefile
  api/core/v1alpha1/webui_types.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
  cmd/operator/main.go
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_webuis.yaml
  examples/mo-cluster.yaml
  pkg/controllers/mocluster/controller.go
  pkg/controllers/webui/resource.go
Labels: can-merge, bug

#221 test: add matrixonecluster rolling-update test
  test/e2e/matrixonecluster_test.go
Labels: test-ci, can-merge

#223 feat: add cn basic ut
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/controller_test.go
Labels: test-ci

#228 feat: add basic dn status
  api/core/v1alpha1/dnset_helpers.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  pkg/controllers/dnset/controller.go
  pkg/controllers/dnset/status.go
Labels: feature

#230 refactor: add reason types
  Makefile
  pkg/controllers/common/reason_types.go
  pkg/controllers/dnset/controller.go
  pkg/controllers/logset/controller.go
Labels: code-refactoring

#231 Fix the start script issue and add some minor improvements
  api/core/v1alpha1/common_types.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_webuis.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_webuis.yaml
  hack/kind-e2e.sh
  pkg/controllers/common/common.go
  pkg/controllers/dnset/const.go
  pkg/controllers/logset/configmap.go
Labels: improvement, bug, api-change

#236 use mem-engine end to end deployment
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/cnset_webhook.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  hack/kind-e2e.sh
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/controller_test.go
  pkg/controllers/cnset/resource.go
  pkg/controllers/common/common.go
  pkg/controllers/dnset/resource.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/sts.go
  test/e2e/logset_test.go
  test/e2e/matrixonecluster_test.go
Labels: improvement

#237 feat: add cn status
  api/core/v1alpha1/cnset_helpers.go
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  pkg/controllers/cnset/const.go
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/status.go
Labels: feature

#239 fix: scale-out and failover should not cause rolling-update
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  pkg/controllers/common/common.go
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/configmap_test.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/sts.go
  pkg/controllers/logset/sts_test.go
  test/e2e/logset_test.go
Labels: bug

#235 feat: add basic webui ut
  pkg/controllers/webui/const.go
  pkg/controllers/webui/controller.go
  pkg/controllers/webui/controller_test.go
Labels: test-ci

#240 test: add end to end sql test in e2e
  go.mod
  go.sum
  test/e2e/matrixonecluster_test.go
  test/e2e/sql/sql.go
  test/e2e/suite_test.go
  test/e2e/util/portforward.go
Labels: improvement

#241 test: add logset failover E2E case
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  go.mod
  go.sum
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/store.go
  runtime/pkg/reconciler/reconciler.go
  test/e2e/logset_test.go
  test/e2e/matrixonecluster_test.go
  test/e2e/sql/sql.go
  test/e2e/util/patch.go
Labels: improvement
