Repository matrixorigin/matrixone-operator, pull requests merged in 2022-11, with the labels that each got.

#275 allow set imagePullPolicy in mo-cluster CR
  api/core/v1alpha1/matrixonecluster_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  docs/reference/api-reference.md
  pkg/controllers/mocluster/controller.go
Labels: feature

#271 fix: service update
  api/core/v1alpha1/cnset_types.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  examples/mo-on-local.yaml
  hack/kind-e2e.sh
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/controller_test.go
  pkg/controllers/cnset/resource.go
  pkg/controllers/dnset/controller.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/webui/const.go
  pkg/controllers/webui/controller.go
  pkg/controllers/webui/resource.go
  test/e2e/cnset_test.go
  test/e2e/logset_test.go
  test/e2e/suite_test.go
Labels: bug

#278 feat: add release action
  .github/workflows/release.yml
  README.md
Labels: feature, can-merge

#279 fix: data-dir should be set to persistent volume
  pkg/controllers/common/fileservice.go
  pkg/controllers/dnset/resource_test.go
Labels: bug

#282 fix: sync pvc retention policy from mo to logservice
  pkg/controllers/logset/sts.go
  pkg/controllers/logset/sts_test.go
  pkg/controllers/mocluster/controller.go
  pkg/controllers/mocluster/controller_test.go
Labels: can-merge, bug
