Repository matrixorigin/matrixone-operator, pull requests merged in 2022-08, with the labels that each got.

#172 perf: udpate reconcile klog level label
  runtime/pkg/reconciler/reconciler.go
Labels: improvement

#174 feat: bootstrap logservice via start script
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/toml_config.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_logsets.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  deploy/crds/matrixone.matrixorigin.cn_logsets.yaml
  deploy/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  pkg/controllers/common/common.go
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/discovery.go
  pkg/controllers/logset/sts.go
Labels: feature, can-merge

#175 fix: make operator runnable
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/groupversion_info.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/matrixonecluster_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  charts/matrixone-operator/templates/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  cmd/operator/main.go
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/matrixone.matrixorigin.cn_matrixoneclusters.yaml
  examples/logset.yaml
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/discovery.go
  pkg/controllers/logset/sts.go
Labels: improvement, can-merge

#177 feat: bootstrap logset
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/toml_config.go
  api/core/v1alpha1/toml_config_test.go
  examples/logset.yaml
  pkg/controllers/common/common.go
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/discovery.go
  pkg/controllers/logset/sts.go
  runtime/pkg/reconciler/reconciler.go
Labels: feature, can-merge

#178 feat: add printed columns for CRD
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/logset_types.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
Labels: improvement, can-merge

#179 feat: support wait dependencies in reconciler
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/logset_helpers.go
  api/go.mod
  api/go.sum
  runtime/pkg/reconciler/actor.go
  runtime/pkg/reconciler/dependant.go
  runtime/pkg/reconciler/reconciler.go
Labels: feature, can-merge

#180 feat: add failover for logset
  api/core/v1alpha1/logset_helpers.go
  api/core/v1alpha1/logset_types.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  cmd/operator/main.go
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  pkg/controllers/common/common.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/store.go
  pkg/controllers/logset/sts.go
  runtime/pkg/reconciler/actor.go
  runtime/pkg/reconciler/event.go
  runtime/pkg/reconciler/reconciler.go
  runtime/pkg/util/util.go
Labels: feature, can-merge

#181 feat: add matrixonecluster controller to assemble the resources
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/matrixonecluster_helpers.go
  api/core/v1alpha1/matrixonecluster_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  cmd/operator/main.go
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  examples/kustomization.yaml
  examples/logset.yaml
  examples/mo-cluster.yaml
  examples/tiny-cluster.yaml
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/sts.go
  pkg/controllers/mocluster/controller.go
  pkg/controllers/mocluster/controller_test.go
  pkg/infra/aliyun/aliyun.go
  pkg/infra/aws/aws.go
  pkg/infra/tencentcloud/tcloud.go
  runtime/pkg/reconciler/helper.go
Labels: feature, can-merge

#184 feat: cnset and dnset depend on logset
  api/core/v1alpha1/logset_helpers.go
  pkg/controllers/mocluster/controller.go
  runtime/pkg/reconciler/reconciler.go
Labels: feature, can-merge

#185 fix: build error
  pkg/controllers/logset/store.go
Labels: bug

#186 feat: add strategy of cn and dn
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_logsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  cmd/operator/main.go
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_logsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  pkg/controllers/cnset/const.go
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/resource.go
  pkg/controllers/common/common.go
  pkg/controllers/dnset/controller.go
  pkg/controllers/dnset/resource.go
Labels: feature

#187 fix: make cluster runnable
  examples/logset.yaml
  examples/mo-cluster.yaml
  pkg/controllers/cnset/resource.go
Labels: improvement, can-merge

#189 fix: racing issue on bootstrap and refine code
  api/core/v1alpha1/cnset_types.go
  cmd/operator/main.go
  pkg/controllers/cnset/const.go
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/resource.go
  pkg/controllers/cnset/utils.go
  pkg/controllers/common/common.go
  pkg/controllers/dnset/const.go
  pkg/controllers/dnset/controller.go
  pkg/controllers/dnset/resource.go
  pkg/controllers/dnset/utils.go
  pkg/controllers/logset/bootstrap.go
  pkg/controllers/logset/configmap.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/discovery.go
  pkg/controllers/logset/sts.go
  pkg/controllers/mocluster/controller.go
Labels: improvement, can-merge

#190 Aylei/add webhook
  PROJECT
  api/core/v1alpha1/cnset_types.go
  api/core/v1alpha1/cnset_webhook.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/dnset_types.go
  api/core/v1alpha1/dnset_webhook.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/matrixonecluster_webhook.go
  api/core/v1alpha1/webhook.go
  api/go.mod
Labels: feature, can-merge

#192 chore: remove replace in api go mod to simplify dependents
  api/go.mod
  api/go.sum
Labels: improvement, can-merge

#193 fix: operator compliation error
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_cnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_dnsets.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_matrixoneclusters.yaml
  deploy/crds/core.matrixorigin.io_cnsets.yaml
  deploy/crds/core.matrixorigin.io_dnsets.yaml
  deploy/crds/core.matrixorigin.io_matrixoneclusters.yaml
  pkg/controllers/dnset/resource.go
Labels: bug, can-merge

#191 feat: refactor helm charts
  .gitignore
  PROJECT
  charts/matrixone-operator/Chart.yaml
  charts/matrixone-operator/templates/_helpers.tpl
  charts/matrixone-operator/templates/deployment.yaml
  charts/matrixone-operator/templates/role.yaml
  charts/matrixone-operator/templates/role_binding.yaml
  charts/matrixone-operator/values.yaml
  cmd/operator/main.go
  examples/mo-cluster.yaml
  images/operator/Dockerfile
Labels: feature

#195 fix: name typo
  pkg/controllers/cnset/resource.go
  pkg/controllers/dnset/controller.go
  pkg/controllers/dnset/resource.go
Labels: improvement

#197 feat: add webhook deployment
  api/Makefile
  api/core/v1alpha1/cnset_webhook.go
  api/core/v1alpha1/dnset_webhook.go
  api/core/v1alpha1/logset_webhook.go
  api/core/v1alpha1/matrixonecluster_webhook.go
  api/core/v1alpha1/webhook.go
  charts/matrixone-operator/templates/_helpers.tpl
  charts/matrixone-operator/templates/deployment.yaml
  charts/matrixone-operator/templates/webhook-service.yaml
  charts/matrixone-operator/templates/webhook.yaml
  cmd/operator/main.go
  deploy/webhook/kustomization.yaml
  deploy/webhook/kustomizeconfig.yaml
  deploy/webhook/manifests.yaml
Labels: improvement, can-merge

#199 chore: rm useless files
  index.yaml
  packages/matrixone-operator-0.1.0.tgz
  third_part/mo-docker/Dockerfile
  third_part/mo-docker/entrypoint.sh
  third_part/mo-docker/system_vars_config.toml
  tools/bvt-test/Dockerfile
Labels: code-refactoring

#201 chore: optimize helm charts build
  .gitignore
  Makefile
Labels: improvement

#202 [feat] support s3 static credential access for cn/dn
  api/core/v1alpha1/logset_webhook.go
  charts/matrixone-operator/templates/role.yaml
  cmd/operator/main.go
  examples/mo-cluster.yaml
  pkg/controllers/cnset/controller.go
  pkg/controllers/cnset/resource.go
  pkg/controllers/common/common.go
  pkg/controllers/dnset/controller.go
  pkg/controllers/dnset/resource.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/sts.go
  pkg/controllers/mocluster/controller.go
  runtime/pkg/reconciler/errors.go
  runtime/pkg/reconciler/reconciler.go
  runtime/pkg/util/util.go
Labels: feature

#204 feat: add ut and e2e framework
  .gitignore
  Makefile
  api/core/v1alpha1/common_helpers.go
  charts/matrixone-operator/templates/role.yaml
  charts/matrixone-operator/templates/webhook.yaml
  charts/matrixone-operator/values.yaml
  cmd/infra/Pulumi.yaml
  cmd/infra/go.mod
  cmd/infra/go.sum
  cmd/infra/main.go
  cmd/operator/main.go
  go.mod
  go.sum
  hack/e2e.sh
  hack/kind-e2e.sh
  local
  pkg/controllers/cnset/controller.go
  pkg/controllers/logset/controller.go
  pkg/controllers/logset/controller_test.go
  pkg/controllers/logset/sts.go
  pkg/controllers/logset/sts_test.go
  pkg/controllers/webhook/controller.go
  runtime/pkg/fake/actor.go
  runtime/pkg/fake/client.go
  runtime/pkg/fake/event.go
  runtime/pkg/fake/fake.go
  runtime/pkg/fake/util.go
  runtime/pkg/reconciler/actor.go
  runtime/pkg/reconciler/reconciler.go
  test/e2e/creation_test.go
  test/e2e/suite_test.go
Labels: improvement, can-merge
