Repository matrixorigin/matrixone-operator, pull requests merged in 2024-06, with the labels that each got.

#505 fix: cn-pool reclaim should respect storeDrainTimeout
  kind.yaml
  pkg/controllers/cnstore/pooling.go
Labels: configuration changes, Review effort [1-5]: 2, Bug fix

#506 fix: skip CN not found
  pkg/controllers/cnclaim/controller.go
Labels: Review effort [1-5]: 2, Bug fix

#509 fix: AdmissionWebhook name collision
  charts/matrixone-operator/templates/webhook.yaml
Labels: Review effort [1-5]: 1, Bug fix

#511 feat: push image to Aliyun Container Registry
  .github/workflows/release_image.yml
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#513 fix: fixed cn drain skip case
  pkg/controllers/cnstore/controller.go
  pkg/controllers/common/cnstore.go
  pkg/controllers/common/cnstore_test.go
Labels: Bug fix, Tests, Review effort [1-5]: 3

#516 refactor: moves the admission-webhook code into pkg/webhook from api
  Makefile
  api/core/v1alpha1/cnset_webhook.go
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/dnset_webhook.go
  api/core/v1alpha1/logset_helpers.go
  api/core/v1alpha1/logset_types.go
  api/core/v1alpha1/matrixonecluster_webhook.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  cmd/operator/main.go
  go.mod
  go.sum
  pkg/webhook/cnset_webhook.go
  pkg/webhook/cnset_webhook_test.go
  pkg/webhook/common.go
  pkg/webhook/dnset_webhook.go
  pkg/webhook/dnset_webhook_test.go
  pkg/webhook/logset_webhook.go
  pkg/webhook/logset_webhook_test.go
  pkg/webhook/matrixonecluster_webhook.go
  pkg/webhook/matrixonecluster_webhook_test.go
  pkg/webhook/proxy_webhook.go
  pkg/webhook/proxy_webhook_test.go
  pkg/webhook/utils.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_suite_test.go
  pkg/webhook/webui_webhook.go
  test/e2e/matrixonecluster_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4
