Repository matrixorigin/matrixone-operator, pull requests merged in 2024-09, with the labels that each got.

#548 feat: more logs for store draining
  pkg/controllers/cnclaim/controller.go
  pkg/controllers/cnclaim/migrate.go
  pkg/controllers/cnstore/controller.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#549 fix: validate semver setting in webhook
  api/core/v1alpha1/semver_test.go
  pkg/controllers/common/podset.go
  pkg/controllers/common/podset_test.go
  pkg/webhook/cnset_webhook.go
  pkg/webhook/cnset_webhook_test.go
  pkg/webhook/common.go
  pkg/webhook/dnset_webhook_test.go
  pkg/webhook/logset_webhook_test.go
  pkg/webhook/proxy_webhook_test.go
Labels: Bug fix, Tests, Review effort [1-5]: 3

#550 fix: fixed Patch behavior
  go.mod
  go.sum
Labels: Review effort [1-5]: 1, dependencies

#553 feat: support container level securityContext in main container
  api/core/v1alpha1/common_helpers.go
  api/core/v1alpha1/common_types.go
  api/core/v1alpha1/zz_generated.deepcopy.go
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_backupjobs.yaml
  charts/matrixone-operator/templates/crds/core.matrixorigin.io_restorejobs.yaml
  deploy/crds/core.matrixorigin.io_backupjobs.yaml
  deploy/crds/core.matrixorigin.io_restorejobs.yaml
  docs/reference/api-reference.md
  pkg/webhook/common.go
Labels: enhancement, Review effort [1-5]: 2

#551 fix: fixed diagnosis info in pool draining
  pkg/controllers/cnstore/controller.go
  pkg/controllers/cnstore/pooling.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix
